easy_admin:
    site_name: "Experiences back-office"
    design:
        brand_color: '#1ABC9C'
        menu:
            - {label: 'Offer', icon: 'users'}
            - 'Experience'
#            - 'ExperienceVersion'
            - 'Activity'
            - 'Pony'
            - 'Destination'
    entities:
        # List the entity class name you want to manage
        Experience:
            class: App\Entity\Experience
            Controller: App\Controller\ExperienceController
            list:
                fields:
                  - id
                  - title
                  - slug
                  - versions
                actions:
                    - show
                filters:
                    - { property: 'Title' }
                    - { property: 'id' }
            new:
              fields:
                - title
            edit:
                fields:
                    - id
                    - title
                    - { property: 'slug', type_options: { disabled: true } }
                actions:
                    - { name: 'experience_publish', label: 'Publish', type: 'route' }
            show:
              fields:
                - id
                - title
                - slug
                - state
                - { property: 'versions', template: 'experience/_versions_fields.html.twig', label: '' }

        ExperienceVersion:
            class: App\Entity\ExperienceVersion
            show:
                fields:
                    - version
                    - title
                    - description
            edit:
                fields:
                    - title
                    - description
        Activity:
            class: App\Entity\Activity
        Pony:
            class: App\Entity\Pony
            list:
                batch_actions: ['delete']
                filters:
                    - property: 'birthdate'
                      type: 'App\Form\DateCalendarFilterType'
        Destination:
            class: App\Entity\Destination
            controller: App\Controller\DestinationController
            disabled_actions: ['new', 'edit', 'delete']
