easy_admin:
    site_name: "Experiences back-office"
    design:
        brand_color: '#1ABC9C'
        menu:
            - {label: 'Offer', icon: 'users'}
            - 'Experience'
            - 'Activity'
            - 'Pony'
            - 'Destination'
    entities:
        # List the entity class name you want to manage
        Experience:
            class: App\Entity\Experience
            Controller: App\Controller\ExperienceController
            templates:
                show: 'experience/show.html.twig'
            list:
                fields:
                  - id
                  - title
                  - slug
                  - versions
                actions:
                    - show
                filters:
                    - { property: 'Title' }
                    - { property: 'id' }
            new:
              fields:
                - title
            edit:
                fields:
                    - id
                    - title
                    - { property: 'slug', type_options: { disabled: true } }
            show:
              fields:
                - id
                - title
                - slug
              actions:
                - { name: 'experience_add_version', type: 'route', label: 'Add version'}
        ExperienceVersion:
            class: App\Entity\ExperienceVersion
            templates:
                edit: 'experienceVersion/edit.html.twig'
            disabled_actions:
                ['delete', 'list']
            show:
                fields:
                    - version
                    - title
                    - description
            edit:
                fields:
                    - title
                    - description
                actions:
                    - { name: 'request_feedback', template: 'experienceVersion/_request_feedback_action.html.twig' }
                    - { name: 'approve', template: 'experienceVersion/_approve_action.html.twig', icon: 'fa-check' }
                    - { name: 'reject', template: 'experienceVersion/_reject_action.html.twig'}

        Activity:
            class: App\Entity\Activity
        Pony:
            class: App\Entity\Pony
            list:
                batch_actions: ['delete']
                filters:
                    - property: 'birthdate'
                      type: 'App\Form\DateCalendarFilterType'
        Destination:
            class: App\Entity\Destination
            controller: App\Controller\DestinationController
            disabled_actions: ['new', 'edit', 'delete']
