easy_admin:
    site_name: "Experiences back-office"
    design:
        brand_color: '#1ABC9C'
        menu:
            - {label: 'Offer', icon: 'users'}
            - 'Experience'
            - 'Activity'
            - 'Pony'
            - 'Destination'
    entities:
        # List the entity class name you want to manage
        Experience:
            class: App\Entity\Experience
            controller: App\Controller\ExperienceController
            templates:
                edit: 'experience/edit.html.twig'
            list:
                filters:
                    - { property: 'Title' }
                    - { property: 'id' }
            edit:
                fields:
                    - id
                    - title
                    - description
                actions:
                    - { name: 'experience_publish', type: 'route', template: 'experience/_publish_action.html.twig' }
                    - { name: 'experience_ask_feedback', type: 'route', template: 'experience/_ask_feedback_action.html.twig' }
                    - { name: 'experience_approve', type: 'route', template: 'experience/_approve_action.html.twig' }

        Activity:
            class: App\Entity\Activity
        Pony:
            class: App\Entity\Pony
            list:
                batch_actions: ['delete']
                filters:
                    - property: 'birthdate'
                      type: 'App\Form\DateCalendarFilterType'
        Destination:
            class: App\Entity\Destination
            controller: App\Controller\DestinationController
            disabled_actions: ['new', 'delete']
