framework:
    workflows:
        experiences:
            marking_store:
                type: single_state
                arguments:
                    - state
            supports:
                -  App\Entity\Experience
            places:
                - new
                - needs_review
                - reviewed
                - published
            transitions:
                feedback:
                    from: [new, published, reviewed]
                    to: needs_review
                approve:
                    from: [new, needs_review]
                    to:   reviewed
                publish:
                    from: reviewed
                    to:   published
        experience_versions:
            marking_store:
                type: single_state
                arguments:
                    - state
            supports:
                - App\Entity\ExperienceVersion
            places:
                - writing
                - needs_review
                - accepted
            transitions:
                request_feedback:
                    from: [writing]
                    to: needs_review
                approve:
                    from: [needs_review]
                    to:   accepted
                reject:
                    from: needs_review
                    to:   writing
